name: Build and Release

on:
  push:
    branches:
      - master  # Change if your main branch is named differently

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore "Remote control/Remote control.csproj"

      - name: Build project
        run: dotnet build "Remote control/Remote control.csproj" --configuration Release --no-restore

      - name: Find executable
        id: find-exe
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path "Remote control\bin\Release\net9.0-windows" -Filter "*.exe" | Select-Object -First 1
          if (-not $exe) {
            Write-Error "EXE not found!"
            exit 1
          }
          echo "EXE_PATH=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create GitHub Release and upload exe
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: ${{ env.EXE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
