name: Build and Release

on:
  push:
    branches:
      - master  # Change to your branch name if needed
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build "Remote control/Remote control.csproj" --configuration Release --no-restore

      - name: Locate built .exe
        id: find-exe
        run: |
          $exePath = Get-ChildItem -Recurse -Filter "*.exe" -Path .\Remote control\bin\Release\net9.0-windows | Select-Object -First 1
          echo "EXE_PATH=$($exePath.FullName)" >> $env:GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: ${{ env.EXE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
