name: Build Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish self-contained executable
        run: dotnet publish "Remote control/Remote control.csproj" -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RemoteControlBuild
          path: ./publish
